---
name: Tests

on:
  workflow_call:
  pull_request:

jobs:
  unittests:
    strategy:
      matrix:
        platform: ["platform=macOS"]
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Test Chess
        run: xcodebuild -project Chess.xcodeproj
                        -scheme Chess-Tests test
                        -destination "${{ matrix.platform }}"
...
